version: "3.8"
services:
  client:
    container_name: client_container
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - api
    restart: always
  api:
    container_name: api_container
    build: ./server
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: always
  mongo:
    container_name: mongo_container
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"

volumes:
  apiDB:
